repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: .gitlab-ci.yml
      - id: check-json
      - id: check-ast
      - id: requirements-txt-fixer
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.1
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-dependabot
      - id: check-github-actions
      - id: check-github-workflows
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.33.0
  #   hooks:
  #     - id: markdownlint
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.259'
    hooks:
      - id: ruff
