name: release
concurrency: release
on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: '3.11'
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
      branchName: ${{ steps.gitversion.outputs.BranchName }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: 5.12.0
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2
        with:
          useConfigFile: true

  test:
    runs-on: ubuntu-latest
    needs:
      - version
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Install Helm

      - name: pip upgrade
        run: python -m pip install --upgrade pip

      - uses: pre-commit/action@v3.0.0
        name: pre-commit

      - name: Install tox
        run: pip install --upgrade tox

      - name: tox
        run: tox

      - name: fix code coverage paths
        run: |
          sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage-reports/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectVersion=${{ needs.version.outputs.semVer }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
